FROM python:3.12-slim

WORKDIR /app
RUN apt-get update && apt-get install -y --noinstall-recommends\
    build-essential\
    libpq-dev\ 
    && rm -rf /var/lib/apt/lists/*

COPY . /app/

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 3000

CMD ["python", "server.py"]